version: "3.9"

services:
  speedtest:
    image: ghcr.io/YOUR_GITHUB_USERNAME/speedtest-discord:latest
    secrets:
      - source: discord_webhook_url
        target: discord_webhook_url
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro

secrets:
  discord_webhook_url:
    external: true
